import { describe, expect, test } from "bun:test";

import { nextAppAdapter } from "../src/init/adapters/next-app";
import { INIT_ALIASES, type InitAdapterInput } from "../src/init/types";

const ROOT = "/project";
const SOURCE_ROOT = `${ROOT}/src`;
const LAYOUT = `${SOURCE_ROOT}/app/layout.tsx`;

const GENERATED_LAYOUT = `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={\`\${geistSans.variable} \${geistMono.variable} antialiased\`}>
        {children}
      </body>
    </html>
  );
}
`;

describe("W6 Next App Router adapter", () => {
  test("integrates the current generated layout without replacing generated work", () => {
    const result = nextAppAdapter.plan(input(GENERATED_LAYOUT));

    expect(result.diagnostics).toEqual([]);
    expect(result.instructions).toEqual([]);
    expect(result.files).toHaveLength(1);

    const content = result.files[0]!.content;
    expect(content).toContain('import type { Metadata } from "next";');
    expect(content).toContain('import { Geist, Geist_Mono } from "next/font/google";');
    expect(content.indexOf('from "next"')).toBeLessThan(content.indexOf('from "next/font/google"'));
    expect(content).toContain('import "@mantine/core/styles.css";');
    expect(content).toContain(
      'import { MantineProvider, ColorSchemeScript, mantineHtmlProps } from "@mantine/core";',
    );
    expect(content).toContain('import { theme } from "@/lib/theme";');
    expect(content).toContain("export const metadata: Metadata = {");
    expect(content).toContain("const geistSans = Geist({");
    expect(content).toContain('<html lang="en" {...mantineHtmlProps}>');
    expect(content).toContain("<head>\n        <ColorSchemeScript />\n      </head>");
    expect(content).toContain(
      "<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>",
    );
    expect(content).toContain("<MantineProvider theme={theme}>{children}</MantineProvider>");
  });

  test("preserves populated head, document props, single quotes and existing provider props", () => {
    const source = `import { MantineProvider } from '@mantine/core';
import './globals.css';

export const metadata = { title: 'Kept' };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <meta name='application-name' content='Kept' />
      </head>
      <body data-shell='kept'>
        <MantineProvider defaultColorScheme='dark'>{children}</MantineProvider>
      </body>
    </html>
  );
}
`;

    const result = nextAppAdapter.plan(input(source));
    expect(result.diagnostics).toEqual([]);

    const content = result.files[0]!.content;
    expect(content).toContain("import '@mantine/core/styles.css';");
    expect(content).toContain(
      "import { ColorSchemeScript, mantineHtmlProps } from '@mantine/core';",
    );
    expect(content).toContain("import { theme } from '@/lib/theme';");
    expect(content).toContain("<html lang='en' suppressHydrationWarning {...mantineHtmlProps}>");
    expect(content).toContain("<meta name='application-name' content='Kept' />");
    expect(content).toContain("<ColorSchemeScript />");
    expect(content).toContain("<body data-shell='kept'>");
    expect(content).toContain(
      "<MantineProvider defaultColorScheme='dark' theme={theme}>{children}</MantineProvider>",
    );
    expect(content).toContain("export const metadata = { title: 'Kept' };");
  });

  test("a second pass proposes no entry mutation", () => {
    const first = nextAppAdapter.plan(input(GENERATED_LAYOUT));
    const transformed = first.files[0]!.content;
    const second = nextAppAdapter.plan(input(transformed));

    expect(second).toEqual({ files: [], instructions: [], diagnostics: [] });
  });

  test("refuses an unsafe dynamic layout with zero file output", () => {
    const source = `const layout = makeLayout();
export default layout;
`;
    const result = nextAppAdapter.plan(input(source));

    expect(result.files).toEqual([]);
    expect(result.instructions).toEqual([]);
    expect(result.diagnostics).toHaveLength(1);
    expect(result.diagnostics[0]!.code).toBe("init-source-unsupported");
    expect(result.diagnostics[0]!.message).toContain(LAYOUT);
    expect(result.diagnostics[0]!.message).toContain("manually");
  });
});

function input(layoutSource: string): InitAdapterInput {
  return {
    framework: "next-app",
    aliases: INIT_ALIASES,
    project: {
      layout: {
        root: ROOT,
        sourceRoot: SOURCE_ROOT,
        tsconfigPath: `${ROOT}/tsconfig.json`,
        configPath: `${ROOT}/manteen.json`,
        themePath: `${SOURCE_ROOT}/lib/theme.ts`,
        themeImport: "@/lib/theme",
      },
      files: new Map([[LAYOUT, layoutSource]]),
      declaredDependencies: new Map(),
    },
  };
}
