import { dirname, relative, sep } from "node:path";

import type { SourceFile } from "ts-morph";

export const MANTINE_CORE_STYLES = "@mantine/core/styles.css";

export const INIT_STYLES_SOURCE = `/* Generated by manteen. Put project overrides in the host stylesheet imported after this file. */
`;

/** A relative ESM/CSS side-effect import from a framework entry to the managed file. */
export function managedStylesImport(entryPath: string, stylesPath: string): string {
  const path = relative(dirname(entryPath), stylesPath).split(sep).join("/");
  return path.startsWith(".") ? path : `./${path}`;
}

/**
 * Keep the two owned style imports adjacent and before every host stylesheet.
 * Value imports retain their relative order; only these two side-effect imports
 * move. Calling this twice is byte-stable after ts-morph formatting settles.
 */
export function ensureManagedStyleImports(source: SourceFile, managedImport: string): void {
  for (const declaration of [...source.getImportDeclarations()]) {
    const specifier = declaration.getModuleSpecifierValue();
    if (specifier === MANTINE_CORE_STYLES || specifier === managedImport) declaration.remove();
  }

  const firstHostStyle = source
    .getImportDeclarations()
    .findIndex((declaration) =>
      /\.(?:css|scss|sass|less)$/.test(declaration.getModuleSpecifierValue()),
    );
  const index = firstHostStyle < 0 ? 0 : firstHostStyle;
  source.insertImportDeclarations(index, [
    { moduleSpecifier: MANTINE_CORE_STYLES },
    { moduleSpecifier: managedImport },
  ]);
}
