export {
  AuthorConformanceError,
  type AuthorConformanceFailure,
  type AuthorConformanceFailureCode,
  type AuthorConformanceInspection,
  type AuthorProfile,
  buildIndex,
  type CompileResult,
  compileRegistry,
  createWireValidator,
  FILE_TYPE,
  type FileRole,
  ITEM_TYPE,
  inspectAuthorConformance,
  type Kind,
  type MantineItem,
  type MantineRegistry,
  planRegistryWrite,
  type RegistryOutputDiagnostic,
  RegistryOutputError,
  type RegistryOutputMarker,
  type RegistryWriteOptions,
  type RegistryWriteOutcome,
  type RegistryWritePlan,
  recoverRegistryWrite,
  type StylesApiEvidenceMapping,
  summarizeThemeFragment,
  THEME_CHANNELS,
  type ThemeChannelName,
  type ThemeSummary,
  type ThemeSummaryChannel,
  type ThemeSummaryComponent,
  toWireItem,
  validateCatalog,
  type WireItem,
  writeRegistry,
} from "./build-registry";

export {
  type MergeConflict,
  type MergeOptions,
  type MergeResult,
  mergeThemeSource,
} from "./merge-theme";
