export {
  AuthorConformanceError,
  type AuthorConformanceFailure,
  type AuthorConformanceFailureCode,
  type AuthorConformanceInspection,
  type AuthorEvidenceMapping,
  type AuthorProfile,
  buildIndex,
  type CompileResult,
  compileRegistry,
  createWireValidator,
  FILE_TYPE,
  type FileRole,
  ITEM_TYPE,
  inspectAuthorConformance,
  inspectThemeFragmentImports,
  type Kind,
  type MantineItem,
  type MantineRegistry,
  type PropsEvidenceMapping,
  planRegistryWrite,
  type RegistryOutputDiagnostic,
  RegistryOutputError,
  type RegistryOutputMarker,
  type RegistryWriteOptions,
  type RegistryWriteOutcome,
  type RegistryWritePlan,
  recoverRegistryWrite,
  type StylesApiEvidenceMapping,
  summarizeThemeFragment,
  THEME_CHANNELS,
  type ThemeChannelName,
  ThemeFragmentImportError,
  type ThemeFragmentImportFailure,
  type ThemeSummary,
  type ThemeSummaryChannel,
  type ThemeSummaryComponent,
  toWireItem,
  type UsageEvidenceMapping,
  validateCatalog,
  type WireItem,
  writeRegistry,
} from "./build-registry";

export {
  type MergeConflict,
  type MergeOptions,
  type MergeResult,
  mergeThemeSource,
} from "./merge-theme";

export {
  applyScaffold,
  isScaffoldItemName,
  planScaffold,
  SCAFFOLD_ITEM_NAME,
  type ScaffoldApplyOutcome,
  type ScaffoldDiagnostic,
  ScaffoldError,
  type ScaffoldInput,
  type ScaffoldPlan,
  type ScaffoldPlannedFile,
  type ScaffoldPreservedFile,
} from "./scaffold";
export { SCAFFOLD_TEMPLATES, type ScaffoldTemplate } from "./scaffold-templates";
