export {
  buildIndex,
  type CompileResult,
  compileRegistry,
  createWireValidator,
  FILE_TYPE,
  type FileRole,
  ITEM_TYPE,
  type Kind,
  type MantineItem,
  type MantineRegistry,
  planRegistryWrite,
  type RegistryOutputDiagnostic,
  RegistryOutputError,
  type RegistryOutputMarker,
  type RegistryWriteOptions,
  type RegistryWriteOutcome,
  type RegistryWritePlan,
  recoverRegistryWrite,
  toWireItem,
  validateCatalog,
  type WireItem,
  writeRegistry,
} from "./build-registry";

export {
  type MergeConflict,
  type MergeOptions,
  type MergeResult,
  mergeThemeSource,
} from "./merge-theme";
